apiVersion: apps/v1
kind: Deployment
metadata:
  name: autosigner
  labels:
    app: autosigner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autosigner
  template:
    metadata:
      labels:
        app: autosigner
    spec:
      containers:
      - name: autosigner
        image: karmab/autosigner:latest
